### ISSUE TITLE
is_dir() not working

### ISSUE THREAD

**Issue by CalebQ42** [CalebQ42/PEDCO#2]
in updatecontent.php I want the part that goes
`if ($num>2){
        if (endsWith($v,".html") && !is_dir("projects/"+$v)){
            echo "<a class='button' href='projects/",$v, "'>" ,rtrim($v,".html"), "</a>  ";
        }else if (endsWith($v,".php") && !is_dir("projects/"+$v)){
            echo "<a class='button' href='projects/", $v , "'>" , rtrim($v,".php") , "</a>  ";
        }else{
            echo "<a class='button' href='projects/" , $v , "'>", $v , "</a>  ";
        }
    }`
to have a check for is_dir("projects/"+$v) at the end instead of straight else, but it doesn't like to work for no reason.

**Comment by xianc78** [comment]
Don't have the pages be separate files. I was making a framework that has 1 main page that loads "pages" from SQL data. So we don't need this menu script.

**Comment by CalebQ42** [comment]
Definately sounds good, I'm making a executable that can turn BBCode into HTML (I just uploaded it) so that the maintainer can easily update everything. Currently only has support for [img] [b] [s] [i] [u], but I plan to add more ([url] is going to be my next priority)

**Comment by CalebQ42** [comment]
[url] BBCode should definately work now

**Comment by xianc78** [comment]
Sadly, you can't run an executable with PHP, so you need to create a PHP script to convert BBCode to HTML. Also, since everyone else on the team knows HTML, we don't need the BBCode converter until we let PEDCO use our page creator. The we could use BBCode for blog posts and comments though.

**Comment by CalebQ42** [comment]
Yeah, I was mainly using it for blog posts and comments.. You can execute BBConverter from php using something like:
'$in = escapeshellarg($in);
'$out = shell_exec('BBConverter '.$in);
If anything it might need "./" in front of BBConverter, but BBConverter is a native linux executable so it will work server side without problem.
