### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by CalebQ42** [CalebQ42/PEDCO#4]
I noticed last night that you are using md5 and I just wanted to say, if you weren't already aware, that md5 is no longer secure for storing passwords. Honestly it's not that big of a deal simply because I don't think anyone is going to try to hack the website, I just wanted to make you aware if you weren't already.

**Comment by dwmikesell** [comment]
I wouldn't worry about it as far as PW encryption. I think you're right
that the odds are being hacked are low and that most of the vital
information will be stored on Google anyhow, meaning that its security will
constantly be updated.

On Thu, May 12, 2016 at 9:30 AM, Belac Darkstorm notifications@github.com
wrote:

> I noticed last night that you are using md5 and I just wanted to say, if
> you weren't already aware, that md5 is no longer secure for storing
> passwords. Honestly it's not that big of a deal simply because I don't
> think anyone is going to try to hack the website, I just wanted to make you
> aware if you weren't already.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/CalebQ42/PEDCO/issues/4

## 

_David W. Mikesell_
_Schoology Contract Trainer_
_Serving the needs of Education and Corporate Client Training Needs_

_Website_: http://www.schoology.com
_Home/Cell Phone:_ (262) 945-1972
_Email:_ dwmikesell@gmail.com

**Comment by xianc78** [comment]
I was thinking about sha1 but to my knowledge, that really isn't secure either, but I'm pretty sure that no one would want to hack the site since it's not something like Facebook or PayPal. Plus, if someone where to hack into the database, there is no need to break into an account because they can edit pages directly.
