### ISSUE TITLE
New Discussion

### ISSUE THREAD

**Issue by CalebQ42** [CalebQ42/PEDCO#5]
The other issue was running a bit long and I don't feel like scrolling all the way down anymore.

**Comment by dwmikesell** [comment]
How you think I feel heading sometimes? Haha

**Comment by dwmikesell** [comment]
Heading should be grading... Wow autocorrect..

**Comment by CalebQ42** [comment]
I'm probably going to work on making the button functions with the new fancyness unless you need me elsewhere. I already have the youtube and link done. Feel free to give suggestions, I'm currently working on an idea that popped into my head.

**Comment by CalebQ42** [comment]
for the color selector, what do you think would be the best way? I now a `<select>` with some of the html colors and probably the website's main colors, but how do you want the color to be previewed? My first thought is to have the background of the `<option>` the color.

**Comment by dwmikesell** [comment]
That'll be fine for the color

**Comment by CalebQ42** [comment]
Worked out the pictureness. Uploaded the php script

**Comment by CalebQ42** [comment]
How does this look for the image add? (besides adding css styling) https://goo.gl/photos/1HWMsPNCN3xXxwP3A

**Comment by CalebQ42** [comment]
the select box has URL, Upload, and Previously Uploaded with the row below it changing for each one.

**Comment by dwmikesell** [comment]
Looks boss.

On Tue, May 17, 2016 at 11:35 AM, Belac Darkstorm notifications@github.com
wrote:

> the select box has URL, Upload, and Previously Uploaded with the row below
> it changing for each one.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/CalebQ42/PEDCO/issues/5#issuecomment-219776369

## 

_David W. Mikesell_
_Schoology Contract Trainer_
_Serving the needs of Education and Corporate Client Training Needs_

_Website_: http://www.schoology.com
_Home/Cell Phone:_ (262) 945-1972
_Email:_ dwmikesell@gmail.com

**Comment by xianc78** [comment]
Do you want me to do the presentation slide.

**Comment by xianc78** [comment]
I've noticed that you used curly braces in if statements in your CoffeScript code. Just to let you know, CoffeeScript doesn't use if statements; instead, it uses tab indentations.

**Comment by CalebQ42** [comment]
Yeah, meant to fix that

**Comment by CalebQ42** [comment]
I think I have the upload done, just haven't uploaded it yet

**Comment by CalebQ42** [comment]
Finished debugging the upload so it can now be moved to the server. I have it point to the folder `../Pictures`

**Comment by CalebQ42** [comment]
I also removed the braces

**Comment by CalebQ42** [comment]
I made the insertAtCursor function better so you can now select some text then hit add bold and it'll put bold tags around the selected text.

**Comment by CalebQ42** [comment]
Moved the insertAtCursor function to the coffee file and moved the image function to the php. Just makes sure all functions can access the functions they need. Implemented the changes mikesell and I made in Mod 10 with a couple other things I caught.

**Comment by dwmikesell** [comment]
The spaces in the links caused the whole link process to die. Never even
searches through the db or find the index again. I'll try employing the
same .pho process as the editor and mobile did to fix that late tonight or
tomorrow.

**Comment by CalebQ42** [comment]
Did you have success in your fix?

**Comment by dwmikesell** [comment]
I did.

On Mon, May 23, 2016 at 9:45 AM, Belac Darkstorm notifications@github.com
wrote:

> Did you have success in your fix?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/CalebQ42/PEDCO/issues/5#issuecomment-221001250

## 

_David W. Mikesell_
_Schoology Contract Trainer_
_Serving the needs of Education and Corporate Client Training Needs_

_Website_: http://www.schoology.com
_Home/Cell Phone:_ (262) 945-1972
_Email:_ dwmikesell@gmail.com

**Comment by dwmikesell** [comment]
Still having trouble with the picture piece working. Let's walk through
that today a bit Caleb. I fixed the position piece, but it will not insert
for a URL or Upload. I did add upload.php back onto the server.

On Mon, May 23, 2016 at 9:47 AM, David Mikesell dwmikesell@gmail.com
wrote:

> I did.
> 
> On Mon, May 23, 2016 at 9:45 AM, Belac Darkstorm <notifications@github.com
> 
> > wrote:
> > 
> > Did you have success in your fix?
> > 
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > https://github.com/CalebQ42/PEDCO/issues/5#issuecomment-221001250
> 
> ## 
> 
> _David W. Mikesell_
> _Schoology Contract Trainer_
> _Serving the needs of Education and Corporate Client Training Needs_
> 
> _Website_: http://www.schoology.com
> _Home/Cell Phone:_ (262) 945-1972
> _Email:_ dwmikesell@gmail.com

## 

_David W. Mikesell_
_Schoology Contract Trainer_
_Serving the needs of Education and Corporate Client Training Needs_

_Website_: http://www.schoology.com
_Home/Cell Phone:_ (262) 945-1972
_Email:_ dwmikesell@gmail.com

**Comment by dwmikesell** [comment]
I built the array in ID instead of name

On Mon, May 23, 2016 at 11:55 AM, David Mikesell dwmikesell@gmail.com
wrote:

> Still having trouble with the picture piece working. Let's walk through
> that today a bit Caleb. I fixed the position piece, but it will not insert
> for a URL or Upload. I did add upload.php back onto the server.
> 
> On Mon, May 23, 2016 at 9:47 AM, David Mikesell dwmikesell@gmail.com
> wrote:
> 
> > I did.
> > 
> > On Mon, May 23, 2016 at 9:45 AM, Belac Darkstorm <
> > notifications@github.com> wrote:
> > 
> > > Did you have success in your fix?
> > > 
> > > —
> > > You are receiving this because you commented.
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/CalebQ42/PEDCO/issues/5#issuecomment-221001250
> > 
> > ## 
> > 
> > _David W. Mikesell_
> > _Schoology Contract Trainer_
> > _Serving the needs of Education and Corporate Client Training Needs_
> > 
> > _Website_: http://www.schoology.com
> > _Home/Cell Phone:_ (262) 945-1972
> > _Email:_ dwmikesell@gmail.com
> 
> ## 
> 
> _David W. Mikesell_
> _Schoology Contract Trainer_
> _Serving the needs of Education and Corporate Client Training Needs_
> 
> _Website_: http://www.schoology.com
> _Home/Cell Phone:_ (262) 945-1972
> _Email:_ dwmikesell@gmail.com

## 

_David W. Mikesell_
_Schoology Contract Trainer_
_Serving the needs of Education and Corporate Client Training Needs_

_Website_: http://www.schoology.com
_Home/Cell Phone:_ (262) 945-1972
_Email:_ dwmikesell@gmail.com
